resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6 # Tamaño de la ventana de muestra
        failure-rate-threshold: 50 # Umbral de tasa de fallos
        wait-duration-in-open-state: 20s # Tiempo de espera en estado abierto
        permitted-number-of-calls-in-half-open-state: 4 # Cantidad permitida de llamadas en estado semiabierto
        slow-call-rate-threshold: 50 # Umbral de tasa para llamadas lentas
        slow-call-duration-threshold: 2s # Duración para considerar una llamada lenta
    instances:
      items: # Nombre del Circuit Breaker
        base-config: defecto

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    io.github.resilience4j: DEBUG